import React from "react";
import "./Hero.css";
import Nav from "./Nav";

const Disclamar = () => {
  return (
    <>
      <div></div>
      <div className="wrapper">
        <Nav />
        <div className="container text-white">
          <p>Updated: November 15, 2021</p>
          <br />
          <p>
            DEGEN SANTAS, DEGEN ELVES, and DEGEN REINDEER are Non-Fungible
            Tokens (NFTs) operating on the Ethereum blockchain (ERC-721). This
            website is only an interface facilitating users to purchase these
            tokens.
            <br />
            <br />
            This website and its connected services are provided “as is” and “as
            available,” without warranty of any kind. Without limiting this, we
            expressly disclaim all warranties, whether expressed, implied, or
            statutory, regarding the website. Using applications on the
            blockchain is associated with a high degree of technological and/or
            other risks. Holders and/or purchasers of the NFT Tokens and
            associated artwork are subject to the Terms & Conditions found on
            this website.
            <br />
            <br />
            Furthermore, users are, without limitation, responsible for
            validating any transactions and contracts generated by and through
            this website before approval. Transactions on the Ethereum network
            cannot be undone, reversed, or restored.
            <br />
            <br />
            NFTs are Non-Fungible Tokens representing ownership of a digital
            artwork only. Accordingly, no information on this website (or any
            other information mentioned therein) is or may be considered to be
            financial advice or an invitation to enter into an agreement for any
            investment purpose. Further, as NFTs represent artwork, nothing on
            this website qualifies or is intended to be an offering of
            securities in any jurisdiction nor does it constitute an offer or an
            invitation to purchase shares, securities, or other financial
            products.
            <br />
            <br />
            Due to the artistic nature of the project, neither this document nor
            the NFTs has been registered with or approved by any regulator in
            any jurisdiction. It remains your responsibility to assure that the
            purchase of NFTs and the associated art is in compliance with laws
            and regulations in your jurisdiction.
            <br />
            <br />
            We undertake no obligation to publicly update or revise any
            information or opinions published on this website. We reserve the
            right to amend information on this website at any time without any
            prior notice.
          </p>
        </div>
      </div>
    </>
  );
};

export default Disclamar;
